import { StyleSheet } from "react-native";
import { theme } from "@/src/styles/theme";

export const styles = StyleSheet.create({
  safeLayout: {
    flex: 1,
    backgroundColor: theme.colors.brand.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xxl,
  },
  section: {
    paddingHorizontal: theme.layout.dashboard.screenPaddingHorizontal,
    marginTop: theme.layout.dashboard.sectionGap,
  },
  sectionBottomPad: {
    paddingBottom: theme.layout.dashboard.sectionGap,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: theme.spacing.sm,
  },
  sectionHeaderLabel: {
    fontSize: theme.typography.size.sm,
    fontWeight: theme.typography.weight.medium,
    color: theme.colors.brand.subtitle,
    letterSpacing: -0.2,
  },
  changeTeamButton: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.brand.subtitle,
    borderRadius: theme.radius.dashboardCard,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  changeTeamButtonText: {
    fontSize: theme.typography.size.xs,
    color: theme.colors.brand.subtitle,
  },
  myTeamCard: {
    height: theme.layout.dashboard.myTeamCardHeight,
    backgroundColor: theme.colors.card,
    borderRadius: theme.radius.dashboardCard,
    padding: theme.spacing.md,
    ...theme.shadow.card,
  },
  myTeamTitleRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    flexWrap: "wrap",
  },
  myTeamNicknameText: {
    fontSize: theme.typography.size.lg,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.text.primary,
  },
  myTeamDaysText: {
    fontSize: theme.typography.size.lg,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.neutralDark,
  },
  myTeamSubText: {
    fontSize: theme.typography.size.sm,
    color: theme.colors.brand.subtitle,
  },
  myTeamStatsRow: {
    flex: 1,
    marginTop: theme.spacing.sm,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  miniStatCard: {
    width: theme.layout.dashboard.myTeamMiniCardSize,
    height: theme.layout.dashboard.myTeamMiniCardHeight,
    borderRadius: theme.radius.dashboardCard,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    justifyContent: "space-between",
  },
  miniStatTonePink: {
    backgroundColor: theme.colors.dashboard.statTonePink,
  },
  miniStatToneYellow: {
    backgroundColor: theme.colors.dashboard.statToneYellow,
  },
  miniStatToneGreen: {
    backgroundColor: theme.colors.dashboard.statToneGreen,
  },
  miniStatIconRow: {
    flexDirection: "row",
  },
  miniStatIconBadge: {
    width: theme.typography.size.md,
    height: theme.typography.size.md,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.card,
    alignItems: "center",
    justifyContent: "center",
  },
  miniStatValue: {
    fontSize: theme.typography.size.sm,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.neutralDark,
  },
  miniStatLabel: {
    fontSize: theme.typography.size.xs,
    color: theme.colors.team.neutralDark,
  },
  mascotBox: {
    width: theme.layout.dashboard.myTeamMascotBox,
    height: theme.layout.dashboard.myTeamMascotBox,
    borderRadius: theme.radius.dashboardCard,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surface,
  },
  mascotEmoji: {
    fontSize: theme.typography.size.xl,
  },
  mascotTeamText: {
    marginTop: theme.spacing.xs,
    fontSize: theme.typography.size.xs,
    color: theme.colors.brand.subtitle,
    fontWeight: theme.typography.weight.medium,
  },
  centerTitleText: {
    fontSize: theme.typography.size.lg,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.neutralDark,
    textAlign: "center",
    marginBottom: theme.spacing.md,
  },
  rankingList: {
    gap: theme.spacing.sm,
  },
  rankingRowWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  rankingRankText: {
    width: theme.spacing.xxl,
    textAlign: "center",
    fontSize: theme.typography.size.lg,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.brand.subtitle,
  },
  rankingRankMyTeam: {
    fontSize: theme.typography.size.xl,
    color: theme.colors.brand.mint,
  },
  rankingPill: {
    flex: 1,
    height: theme.layout.dashboard.rankingRowHeight,
    backgroundColor: theme.colors.card,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    ...theme.shadow.card,
  },
  rankingPillMyTeam: {
    height: theme.layout.dashboard.rankingRowHeightActive,
    borderWidth: theme.layout.dashboard.rankingMyTeamBorderWidth,
    borderColor: theme.colors.brand.mint,
  },
  rankingTeamArea: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
    width: theme.layout.dashboard.myTeamMiniCardSize * 2,
  },
  teamBadge: {
    width: theme.spacing.xxl,
    height: theme.spacing.xxl,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  teamBadgeText: {
    fontSize: theme.typography.size.xs,
    color: theme.colors.brand.subtitle,
    fontWeight: theme.typography.weight.bold,
  },
  rankingTeamName: {
    fontSize: theme.typography.size.sm,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.neutralDark,
  },
  rankingTeamNameMyTeam: {
    color: theme.colors.brand.mint,
  },
  rankingStatArea: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  rankingStatText: {
    width: theme.spacing.xxl,
    fontSize: theme.typography.size.xs,
    color: theme.colors.brand.subtitle,
    textAlign: "center",
  },
  sectionTitleRow: {
    height: theme.layout.dashboard.sectionTitleHeight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: theme.spacing.md,
  },
  sectionTitleText: {
    fontSize: theme.typography.size.lg,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.neutralDark,
    textAlign: "center",
  },
  lineupList: {
    alignItems: "center",
    gap: theme.spacing.xs,
  },
  lineupRow: {
    width: theme.layout.dashboard.lineupRowWidth,
    height: theme.layout.dashboard.lineupRowHeight,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.card,
    ...theme.shadow.card,
    justifyContent: "center",
  },
  lineupNumberArea: {
    position: "absolute",
    left: theme.spacing.lg,
    top: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.lg,
  },
  lineupNumberText: {
    width: theme.spacing.lg,
    textAlign: "center",
    fontSize: theme.typography.size.xl,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.kiaRed,
  },
  lineupDivider: {
    width: StyleSheet.hairlineWidth,
    height: "80%",
    backgroundColor: theme.colors.team.neutralLight,
  },
  lineupNameText: {
    textAlign: "center",
    fontSize: theme.typography.size.lg,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.neutralDark,
  },
  lineupPosText: {
    position: "absolute",
    right: theme.spacing.lg,
    fontSize: theme.typography.size.lg,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.team.kiaRed,
  },
  calendarWrap: {
    width: theme.layout.dashboard.calendarWidth,
    alignSelf: "center",
  },
  calendarHeader: {
    height: theme.layout.dashboard.calendarHeaderHeight,
    backgroundColor: theme.colors.team.neutralLight,
    borderTopLeftRadius: theme.layout.dashboard.calendarRadius,
    borderTopRightRadius: theme.layout.dashboard.calendarRadius,
    flexDirection: "row",
    overflow: "hidden",
  },
  calendarHeaderCell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarHeaderText: {
    fontSize: theme.typography.size.sm,
    fontWeight: theme.typography.weight.bold,
    color: theme.colors.brand.subtitle,
  },
  calendarHeaderTextAccent: {
    color: theme.colors.brand.mint,
  },
  calendarGrid: {
    backgroundColor: theme.colors.card,
    borderBottomLeftRadius: theme.layout.dashboard.calendarRadius,
    borderBottomRightRadius: theme.layout.dashboard.calendarRadius,
    flexDirection: "row",
    flexWrap: "wrap",
    overflow: "hidden",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.team.neutralLight,
  },
  calendarCell: {
    width: theme.layout.dashboard.calendarCellWidth,
    height: theme.layout.dashboard.calendarCellHeight,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.team.neutralLight,
    padding: theme.spacing.xs,
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarCellTopRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarDayText: {
    fontSize: theme.typography.size.sm,
    color: theme.colors.brand.subtitle,
    fontWeight: theme.typography.weight.medium,
  },
  calendarLocationText: {
    fontSize: theme.typography.size.sm,
    color: theme.colors.brand.mint,
    fontWeight: theme.typography.weight.bold,
  },
  calendarLocationSpacer: {
    width: theme.spacing.lg,
    height: theme.spacing.lg,
  },
  calendarOpponentBadge: {
    width: theme.spacing.xxl,
    height: theme.spacing.xl,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarOpponentBadgeSelected: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.brand.mint,
  },
  calendarOpponentText: {
    fontSize: theme.typography.size.xs,
    color: theme.colors.team.neutralDark,
    fontWeight: theme.typography.weight.bold,
  },
  calendarOpponentTextSelected: {
    color: theme.colors.brand.mint,
  },
  calendarEmptySpacer: {
    height: theme.spacing.xl,
  },
  calendarTimeText: {
    fontSize: theme.typography.size.xs,
    color: theme.colors.brand.subtitle,
  },
  calendarTimeSpacer: {
    height: theme.spacing.md,
  },
});
